language: ruby
rvm: 
  - 2.4.1

before_script: 
  - chmod +x ./scripts/cibuild

script: ./_scripts/cibuild

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  
addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false

cache: bundler

notifications:
  email: false
