url: https://ucmercedgamedevelopmentclub.github.io
baseurl: /welcome

# Site settings
title: UC Merced Game Development Club
email: your-email@domain.com
description: "UC Merced's Game Development Club"


# Team names, titles and social links
people:
- name: Me
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Myself
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: I
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Discord
    url: http://discord.gg/5z6THuT
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: itch.io 
    url: https://ucmgdc.itch.io/
  - title: github
    url: https://github.com/UCMercedGameDevelopmentClub

# Postal address (add as many lines as necessary)
address:
  - line: 5200 N. Lake Dr
  - line: Merced, CA 95340

# Build settings
markdown: kramdown
permalink: pretty