url: https://v2.epochml.org
baseurl: /

# Site settings
title: EpochML
email: help@epochml.org
description: "EpochML is building a computational cluster for the IMSA community."


# Team names, titles and social links
motherboard:
- name: Gautham Anne
  pic: 1
  position: CEO
  social:
    - title: envelope
      url: mailto:ganne@epochml.org
- name: Dev Singh
  pic: 2
  position: CTO
  social:
    - title: envelope
      url: mailto:dsingh@epochml.org
- name: Liam Nelson
  pic: 3
  position: CSO
  social:
    - title: envelope
      url: mailto:lnelson@epochml.org
- name: Advait Patel
  pic: 1
  position: CFO
  social:
    - title: envelope
      url: mailto:apatel@epochml.org
- name: Sage Owen
  pic: 2
  position: CRO
  social:
    - title: envelope
      url: mailto:cowen@epochml.org     

shadowboard:
- name: Braeden Cullen
  pic: 1
  position: Shadow CTO
  social:
    - title: envelope
      url: mailto:bcullen@epochml.org

- name: Melanie Cuenca
  pic: 2
  position: Shadow CRO
  social:
    - title: envelope
      url: mailto: mcuenca@epochml.org

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: discord
    url: https://goepoch.ml/discord
  - title: github
    url: https://github.com/epochml

# Postal address (add as many lines as necessary)
address:
  - line: 1500 Sullivan Road
  - line: Aurora, IL 60506

# Build settings
markdown: kramdown
permalink: pretty
