url: https://www.papertrails.co
baseurl: 

# Site settings
title: Paper Trails Co
email: your-email@domain.com
description: "We're two Brooklyn-based travel shamans by the way of Los Angeles, tastefully curating your next travel destination. We create pseudo-itineraries for individuals."


# Team names, titles and social links
people:
- name: Anisha Vasandani
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: David Neudorfer
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/papertrailsco
  - title: instagram
    url: http://instagram.com/papertrailsco

# Postal address (add as many lines as necessary)
address:
  - line: 230 Broadway Unit 3A
  - line: Brooklyn, NY 11211

# Build settings
markdown: kramdown
permalink: pretty
