url: https://alyssabenipayo.github.io
baseurl: ""

# Site settings
title: AB
email: 
description: "Hi, this is Alyssa Benipayo."


# Team names, titles and social links
people:
- name: 
  pic: 
  position: 
  social:
    - title: 
      url: #
    - title: 
      url: #
    - title: 
      url: #

- name: 
  pic: 
  position: 
  social:
    - title: 
      url: #
    - title: 
      url: #
    - title: 
      url: #

- name: 
  pic: 
  position: 
  social:
    - title: 
      url: #
    - title: 
      url: #
    - title: 
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/alyssabenipayo
  - title: linkedin
    url: https://www.linkedin.com/in/alyssabenipayo/

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty