url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: FastLaw
email: bavadim@gmail.com
description: "Сайт команды FastLaw. Описание команды и проектов."


# Team names, titles and social links
people:
- name: Вадим Полулях
  pic: 1.png
  position: Инженер
  description: Архитектор платформ AlfaFactoring и Raiffeisen Business Online. Ведущий инженер проекта iPavlov, МФТИ.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Марат Зайнутдинов
  pic: 2.jpg
  position: Научный консультант
  description: Основатель направления анализа данных в компаниях Segmento и QuantBrothers. Исследователь проекта iPavlov, МФТИ.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Антон Пронин
  pic: 3.jpg
  position: Бизнес наставник
  description: 'Эксперт в области повышения эффективности бизнес-процессов. Директор Центра юридических технологий Фонда Сколково.'
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: github
    url: https://github.com/SageBear

# Postal address (add as many lines as necessary)
address:
  - line: г. Москва, технопарк Сколково

# Build settings
markdown: kramdown
permalink: pretty
