url: https://halcyon-labs.github.io
baseurl: /

# Site settings
title: Halcyon Labs
email: scott.swarthout724@gmail.com
description: "Halcyon Labs is a startup helping startups build their MVPs and launch their businesses."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 35ddff
  secondary: ff9335  
  secondary-dark: 1e1207
  #1e1207
  #333

# Team names, titles and social links
people:
- name: Scott Swarthout
  pic: scott
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: github
      url: #

- name: Derek Metcalf
  pic: derek
  position: Lead Manager
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Dean Miesner
  pic: dean
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url: http://facebook.com/
  - title: linkedin
    url: http://linkedin.com/
  - title: github
    url: http://github.com/halcyon-labs

# Postal address (add as many lines as necessary)
address:
  - line: Farmington Hills, MI 48331

# Build settings
markdown: kramdown
permalink: pretty