url: http://www.fastlaw.io
baseurl: /

# Site settings
title: fastlaw.io
email: info@fastlaw.io
phone: +7 (964) 509-16-37
description: "Site of fastlaw.io. Team and projects."


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/SageBear

# Postal address (add as many lines as necessary)
address:
  - line: г. Москва, технопарк Сколково

# Build settings
markdown: kramdown
permalink: pretty
