url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Itechf 
email: itechfsite@gmail.com
description: "Web development refers in general to the tasks associated with developing websites for hosting via intranet or internet. The web development process includes web design, web content development, client-side/server-side scripting and network security configuration, among other tasks."


# Team names, titles and social links
people:
- name: Nazir Hussain
  pic: nazir.png
  imgAlt: Nazir Hussain Profile Picture
  position: Lead Designer
  social:
    - title: quora
      url: https://www.quora.com
    - title: facebook
      url: https://www.facebook.com/sagar.hussain.5680
    

- name: Iffat Zia Khan
  pic: Iffat Zia Khan.png
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/IffatZia.Khan
  
- name: Amita Srivastav
  pic: Amita Srivastav.png
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - 
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/itechfP
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Jamia Nagar New Delhi
 
  - line: Delhi, India 110025

# Build settings
markdown: kramdown
permalink: pretty
