url: https://www.zerodesignlabs.com
baseurl: "/"

# Site settings
title: ZeroDesignLabs
email: tenzinphuljung7@gmail.com
description: "My name is Tenzin Phuljung, and I am a front-end web developer based in Chicago suburbs."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Random
  pic: 1
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/tenzinpluto
  - title: 
    url:
  - title: linkedin
    url: http://linkedin.com/in/tenzinpluto
  - title: 
    url: 
  - title: github
    url: http://github.com/developertenzin

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty