url: https://epochml.org
baseurl: /

# Site settings
title: Epoch
email: help@epochml.org
description: "EpochML is building a computational cluster for the IMSA community."


# Team names, titles and social links
motherboard:
- name: Gautham Anne
  pic: gautham.png
  position: CEO
  social:
    - title: fas fa-envelope
      url: mailto:ganne@epochml.org
- name: Dev Singh
  pic: dev.jpg
  position: CTO
  social:
    - title: fas fa-envelope
      url: mailto:dsingh@epochml.org
    - title: globe
      url: https://devksingh.com
- name: Liam Nelson
  pic: liam.jpg
  position: CSO
  social:
    - title: fas fa-envelope
      url: mailto:lnelson@epochml.org
- name: Advait Patel
  pic: dne.jpg
  position: CFO
  social:
    - title: fas fa-envelope
      url: mailto:apatel@epochml.org
- name: Sage Owen
  pic: sage.png
  position: CRO
  social:
    - title: fas fa-envelope
      url: mailto:cowen@epochml.org     

shadowboard:
- name: Braeden Cullen
  pic: dne.jpg
  position: Shadow CTO
  social:
    - title: fas fa-envelope
      url: mailto:bcullen@epochml.org
    - title: fab fa-github
      url: https://github.com/BraedenCu

- name: Melanie Cuenca
  pic: melanie.jpg
  position: Shadow CRO
  social:
    - title: fas fa-envelope
      url: mailto:mcuenca@epochml.org
- name: Bhavyaa Chauhan
  pic: dne.jpg
  position: Shadow CFO
  social:
    - title: fas fa-envelope
      url: mailto:bchauhan@epochml.org
- name: Shria Halkoda
  pic: dne.jpg
  position: Shadow CSO
  social:
    - title: fas fa-envelope
      url: mailto:shalkoda@epochml.org

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: discord
    url: https://goepoch.ml/discord
  - title: github
    url: https://github.com/epochml

# Postal address (add as many lines as necessary)
address:
  - line: 1500 Sullivan Road
  - line: Aurora, IL 60506

# Build settings
markdown: kramdown
permalink: pretty
