url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Team Last Responders
email: team@lastresponders.org
description: "Team Last Responders adventures for charity"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Ambulances
ambulances:
- make: Mercedes Sprinter
  year: 2005
  country: Mongolia  
  distance-traveled: 10,000 miles
  modal-id: 1
  pic: 1

- make: Ford E350
  year: 1989
  country: Mali
  distance-traveled: 6,000 miles
  modal-id: 2
  pic: 2

- make: Ford E450
  year: 2003
  country: Peru 
  distance-traveled: 16,000 miles
  modal-id: 3
  pic: 3

# Rally
rallies:
  - modal-id: MongolRally2010
    tag: mongol-rally-2010
    title: Mongol Rally
    year: 2010
    country: Mongolia  
    distance-traveled: 10,000 miles
    img: 1.jpg
  - modal-id: TimbuktuChallenge2011
    tag: timbuktu-challenge-2011
    title: Timbuktu Challenge
    year: 2012
    country: Mongolia  
    distance-traveled: 10,000 miles
    img: 2.jpg
  - modal-id: PanAmericanRally2013
    tag: pan-american-rally-2013
    title: Pan-American Rally
    year: 2014
    country: Mongolia  
    distance-traveled: 16,000 miles
    img: 3.jpg

# Team names, titles and social links
people:
- name: Stephen Jan
  pic: team/profile_sjan.jpg
  position: Director
  social:
    - title: facebook
      url: http://www.facebook.com/sjan828
    - title: linkedin
      url: http://www.linkedin.com/in/sjan828

- name: Cathy Liu
  pic: team/profile_cliu.jpg
  position: Treasurer
  social:
    - title: facebook
      url: http://www.facebook.com/cathy.liu.9083
    - title: linkedin
      url: http://www.linkedin.com/in/cathy-liu-59452a2

- name: Tom Dorwart
  pic: team/profile_tdorwart.jpg
  position: Secratary 
  social:
      - title: facebook
        url: http://www.facebook.com/tom.dorwart.5
      - title: linkedin
        url: http://www.linkedin.com/in/thomas-dorwart-74a8b221
   

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/lastresponders
  - title: facebook
    url: http://facebook.com/lastresponders
  - title: instagram
    url: http://instagram.com/lastresponders

# Postal address (add as many lines as necessary)
address:
  - line: 2373 Broadway 828
  - line: New York, NY 10024

# Build settings
markdown: kramdown
permalink:    /:title/
