url: https://holdonn.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Hold Onn
email: contactoholdonn@gmail.com
description: "La mejor agencia de Marketing y Publicidad en Mazatlán"


# Team names, titles and social links
people:
- name: David Sánchez
  pic: 1
  position: Gerente General
  # social:
  #   - title: twitter
  #     url: #
  #   - title: facebook
  #     url: #
  #   - title: stack-overflow
  #     url: #

- name: Fernando Carvajal
  pic: 2
  position: Producción de Video
  # social:
  #   - title: twitter
  #     url: #
  #   - title: facebook
  #     url: #
  #   - title: linkedin
  #     url: #

- name: Francisco Aguirre
  pic: 3
  position: Edición y Filmación
  # social:
  #   - title: twitter
  #     url: #
  #   - title: facebook
  #     url: #
  #   - title: google-plus
  #     url: #

- name: Salvador Soto
  pic: 3
  position: Administrativo
  # social:
  #   - title: twitter
  #     url: #
  #   - title: facebook
  #     url: #
  #   - title: google-plus
  #     url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/HOLD-ONN-100576375676485/
  - title: instagram
    url: https://www.instagram.com/hold_onn_oficial/?hl=es
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Calle Manuel Burgueño 25, CP 82127
  - line: Mazatlán, Sinaloa, México

# Build settings
markdown: kramdown
permalink: pretty