url: "https://marcosrochedo.github.io"
baseurl: "/marcosrochedo.github.io"

# Site settings
title: Marcos Rocha
email: marcos.paulo.rocha@usp.br
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Marcos Rocha
  pic: 1
  position: Engenheiro Agrônomo
  social:
    - title: linkedin
      url: #
    - title: youtube
      url: #
    - title: github
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/marcos-rocha-2b5a45141/
  - title: facebook
    url: https://www.facebook.com/mpar23
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/marcosrochedo

# Postal address (add as many lines as necessary)
address:
  - line: Departamento de Engenharia de Biossistemas
  - line: Av. Pádua Dias, 11 
          Piracicaba/SP - CEP 13418-900

# Build settings
markdown: kramdown
permalink: pretty
