url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: OpenStreetMap Foundation Japan
email: info@osmf.jp
description: "OpenStreetMapプロジェクトの日本での活動を支援する一般社団法人オープンストリートマップ・ファウンデーション・ジャパン(OpenStreetMap Foundation Japan)の活動報告ページです"


# Team names, titles and social links
people:
- name: 三浦 広志 (Miura Hiroshi)
  pic: 1
  position: 代表理事
  social:
    - title: twitter
      url: https://twitter.com/miurahr
    - title: facebook
      url: # https://www.facebook.com/miurahr

- name: ikiya
  pic: 2
  position: 副理事
  social:
    - title: twitter
      url: # https://twitter.com/ikiya
    - title: facebook
      url: # https://www.facebook.com/kinya.iino

- name: 飯田 哲 (Iida Satoshi, nyampire)
  pic: 3
  position: 副理事
  social:
    - title: twitter
      url: # https://twitter.com/nyampire
    - title: facebook
      url: # https://www.facebook.com/profile.php?id=100002075511572

- name: 古橋 大地 (Furuhashi Taichi, mapconcierge)
  pic: 4
  position: 理事
  social:
    - title: twitter
      url: # https://twitter.com/mapconcierge
    - title: facebook
      url: # https://www.facebook.com/mapconcierge

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/osmfj
  - title: facebook
    url: https://www.facebook.com/groups/osmjapan/
  - title: github
    url: https://github.com/osmfj

# Postal address (add as many lines as necessary)
address:
  - line: 東京都北区
  - line: Kita-ku, Tokyo Japan

# Build settings
markdown: kramdown
permalink: pretty
