# url: https://empmetcogling.gitlab.io/website
# baseurl:

# url: https://empmetcoglin.github.io/
# baseurl:

# url: https://y7kim.github.io
# baseurl: /agency-jekyll-theme/

# https://sites.google.com/site/emcl7joaopessoabrazil/

url: https://empmetcogling.gitlab.io
baseurl:


# Site settings
title: Empirical Methods in Cognitive Linguistics
acronym: EMCL
email: emcl.admin@gmail.com
description: "Official website for Empirical Methods in Cognitive Linguistics"


# Team names, titles and social links
people:
- name: Monica
  pic: rygel
  position: test
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Priya
  pic: priya
  position: TEST
  social:
    - title: twitter
      url: https://twitter.com/priyasilverst
    - title: facebook
      url: https://www.facebook.com/priya.silverstein
    - title: linkedin
      url: https://uk.linkedin.com/in/priya-silverstein-2123894a

- name: Jeff
  pic: jeff
  position: Lecturer & Research Scientist
  social:
    - title: twitter
      url: https://twitter.com/jkbye
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Rémi Gau
  pic: remi
  position: TeSt
  social:
    - title: twitter
      url: https://twitter.com/RemiGau
    - title: facebook
      url: remi.gau1
    - title: google-plus
      url: #

- name: Hans
  pic: 2
  position: TeSt
  social:
    - title: twitter
      url:
    - title: facebook
      url:
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/emcl_workshops
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3rd planet from the sun

# Build settings
markdown: kramdown
permalink: pretty
