url: http://webdevdjm.github.io/


# Site settings
title: Web-Tech Solutions
email: webdevdjm@gmail.com
description: "I provide solutions to all of your technical needs!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00CCCC
  secondary: 00CCCC 
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/davidjcmorse
  - title: facebook
    url:
  - title: bitbucket 
    url: http://bitbucket.org/webdevdjm
  - title: github
    url: http://github.com/webdevdjm

# Postal address (add as many lines as necessary)
address:
  - line:  
  - line:  

# Build settings
markdown: kramdown
permalink: pretty